Database rename
WildCodeSchool/2022-09-JS-Reims-project-3-externatic pull request #33
Opened 2022-12-14 16:27 UTC by Oliv751

2022-12-14 16:35 UTC, rocambille requested changes

2022-12-14 16:35 UTC, rocambille commented on backend/src/models/consultantManager.js
> +const AbstractManager = require("./AbstractManager");
this file is declaring a class, so file name should be in UpperCamelCase

2022-12-14 16:40 UTC, Justine-Merlin requested changes

2022-12-14 16:40 UTC, Justine-Merlin commented on backend/database.sql
> +        id,
Same here.

2022-12-14 16:40 UTC, Justine-Merlin commented on backend/database.sql
> +        id,
Same here.

2022-12-15 09:00 UTC, Oliv751 commented on backend/database.sql
> +        id,
all done , should be ok

2022-12-15 16:25 UTC, rocambille commented
rename the files in a unix system (linux or mac) : windows is case insensitive :grin:

2022-12-19 13:17 UTC, Oliv751 commented
everything should be good now

2022-12-19 13:50 UTC, merged