made login auth in frontend
WildCodeSchool/2022-09-JS-Reims-project-3-externatic pull request #46
Opened 2023-01-04 14:19 UTC by iturnmyscreenon

2023-01-04 14:24 UTC, rocambille commented
conflicts to resolve

2023-01-04 14:37 UTC, iturnmyscreenon commented
conflicts resolved

2023-01-04 15:11 UTC, rocambille requested changes

2023-01-04 15:11 UTC, rocambille commented on frontend/src/main.jsx
> +          <Route path="/CandidateArea" element={<CandidateArea />} />
you can find a better url :)

2023-01-05 08:35 UTC, iturnmyscreenon commented
changed route name

2023-01-06 08:31 UTC, merged