Experience
WildCodeSchool/2022-09-JS-Reims-project-3-externatic pull request #57
Opened 2023-01-18 14:15 UTC by Oliv751

2023-01-18 16:06 UTC, rocambille requested changes

2023-01-18 16:06 UTC, rocambille commented on frontend/src/pages/CandidateExperience.jsx
> +      </div>
remove the div and move your header class inside Header

2023-01-18 16:06 UTC, rocambille commented on frontend/src/pages/CandidateExperience.jsx
> +        <h1>Mes Expériences</h1>
div + h1 : no

2023-01-18 16:06 UTC, rocambille commented on frontend/src/pages/CandidateExperience.jsx
> +          <br />
no br, use css instead

2023-01-18 16:06 UTC, rocambille commented on frontend/src/pages/CandidateExperience.jsx
> +            <h3>{experience.title}</h3>
div + h3 : no

2023-01-18 16:06 UTC, rocambille commented on frontend/src/pages/CandidateExperience.jsx
> +          <div key="">
same key for all elements : no

2023-01-19 09:21 UTC, Oliv751 commented on frontend/src/pages/CandidateExperience.jsx
> +          <div key="">
should be ok now

2023-01-19 09:38 UTC, Oliv751 commented
classname header removed

2023-01-19 10:10 UTC, merged